bot:
  token:
  username:

telegram:
  proxy:
    port: 9150
    host: 127.0.0.1
    type: socks5
  channel-name:
  sync-file-name: last-parse-info

json:
  url:
  date-format: dd/MM/yyyy
  history:
    file-name: history-tracker.json

timezone:
  difference: 4

scheduler:
  delay: 300000

message:
  footer: via СтопКоронавирус.РФ