bot:
  token:
  username:

telegram:
  proxy:
    port: 9150
    host: 127.0.0.1
    type: socks5
  channel-name:

stats:
  root-dir: data
  sync-file-name: last-parse-info
  max-values-name: "max-value-info.json"
  history-tracker-name: "history-tracker.json"

json:
  url: 

operation:
  mode: region
  region-name: "Томская область"

scheduler:
  delay: 60000

slowmode:
  timeout: 600000

message:
  footer: via СтопКоронавирус.РФ