bot:
  token:
  username: 

telegram:
  proxy:
    port: 9150
    host: 127.0.0.1
    type: socks5
  channel-name:
  sync-file-name: last-parse-info

json:
  url:

operation:
  mode: region
  region-name: "Томская область"

scheduler:
  delay: 60000

slowmode:
  timeout: 600000

message:
  footer: via СтопКоронавирус.РФ